Fixed Linux Support
"[16:52:33] Traceback (most recent call last):
  File "./vlcscheduler.py", line 264, in main
    loop.run_until_complete(main_coro())
UnboundLocalError: local variable 'loop' referenced before assignment"

the loop declaration on line 260 should be declared in main, not under the win32 platform test. This causes the program to crash on Linux.